redis:
  image: index.alauda.cn/library/redis:alpine
  ports:
  - '6379'

db:
  image: index.alauda.cn/library/postgres:9.4
  ports:
  - '5432'

vote:
  command: python app.py
  image: private-registry-int-ali-1.alauda.cn:5000/voting-app:latest
  links:
  - redis:redis 
  ports:
    - '5000:80'
    - '5858:5858'

worker:
  image: private-registry-int-ali-1.alauda.cn:5000/voting-worker:latest
  links:
  - redis:redis
  - db:db

result:
  command: nodemon --debug server.js
  image: private-registry-int-ali-1.alauda.cn:5000/voting-result:latest
  links:
  - db:db
  ports:
  - '5001:80'
